name: m_soko
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dots_indicator: ^3.0.0
  fluttertoast: ^8.2.4
  equatable: ^2.0.5
  bloc: ^8.1.2
  meta: ^1.10.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  iconify_flutter: ^0.0.5
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.5
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  get: ^4.6.6
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  flutter_image_slideshow: ^0.1.6
  intl:
  carousel_slider: ^4.2.1
  page_view_dot_indicator: ^2.3.0
  flutter_pannable_rating_bar: ^2.7.2+1
  zego_uikit_prebuilt_call: ^3.18.4
  zego_uikit_signaling_plugin: ^2.7.2
  chat_bubbles: ^1.5.0
  currency_converter: ^0.0.5
  filter_list: ^1.0.2
  implicitly_animated_reorderable_list_2: ^0.5.0
  functional_widget_annotation: ^0.10.0
  just_audio: ^0.9.10 #play audio files
  flutter_video_info: ^1.2.0 #retrieve video metadata
  video_thumbnail: ^0.5.2 #get a thumbnail from a file
  collection: ^1.15.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/auth/
    - assets/tests/
    - assets/tests/mobiles/
    - assets/PropertyImage/
    - assets/icons/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
